### ISSUE TITLE
Match Interfaces

### ISSUE THREAD

**Issue by Snugug** [Snugug/plugabilly#2]
What interfaces should be presented for someone to match against?

These would be something along the lines of "grab all node modules that match the following"
- [ ] Single entry in `keywords`
- [ ] Single entry in `custom package.json attribute`
- [ ] Exclude single entry in `keywords`
- [ ] Exclude single entry in `custom package.json attribute`

**Comment by scottnath** [comment]
@Snugug 
1. What do you foresee the text-to-be-matched?
   - How unique can we make it?
2. `keywords` could be fraught with false positives depending on the phrase
3. I _very much_ prefer a custom attribute
   - custom attr are totally legal as long as we follow the rules
   - best chance at avoiding false positives
4. Can you elaborate on what you mean by "Exclude single entry"?

**Comment by Snugug** [comment]
- As a generic system, want to be able to support multiple options. One project may want `keywords`, one may want `custom attribute`. Would be up to the implementing project to determine _how_ they want to work. Plugabilly will support both.
- Text to be matched is up to end user. I'm thinking either 1/1 text or regex.
- Excludes means "load all except those that match X"
